[package]
name = "zk-cycle-macros"
description = "cycle counting utils"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
readme = "README.md"
resolver = "2"
autotests = false

[lib]
proc-macro = true

[dependencies]
anyhow = { workspace = true }

syn = { version = "1.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
borsh = { workspace = true }

[features]
bench=[]