[package]
name = "sov-demo-prover-host"
version = "0.1.0"
edition = "2021"
publish = false
resolver = "2"

[dependencies]
anyhow = { workspace = true }
borsh = { workspace = true }
hex = { workspace = true }
jsonrpsee = { workspace = true, features = ["http-client", "server"] }
risc0-zkvm = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha2 = { workspace = true }
tokio = { workspace = true }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"

jupiter = { path = "../../../adapters/celestia", features = ["native","bench"] }
demo-stf = { path = "../../demo-stf" }
sov-rollup-interface = { path = "../../../rollup-interface" }
risc0-adapter = { path = "../../../adapters/risc0" }
const-rollup-config = { path = "../../const-rollup-config" }
sov-modules-api = { path = "../../../module-system/sov-modules-api", features = ["native"] }
sov-state = { path = "../../../module-system/sov-state", features = ["native"] }
zk-cycle-utils = { path = "../../../zk-cycle-utils", optional=true }
methods = { path = "../methods" }


[dev-dependencies]
sov-demo-rollup = {path = "../../demo-rollup"}
tempfile = { workspace = true }
once_cell = "1.7.2"
parking_lot = "0.11.1"
prettytable-rs = "^0.10"

[[bench]]
name = "prover_bench"
harness = false

[features]
bench = ["risc0-adapter/bench", "zk-cycle-utils/bench", "methods/bench"]

