[workspace]
resolver = "2"
members = [
	"sdk",
	"jmt",
]


[workspace.dependencies]
# External dependencies
anyhow = "1.0.68"
bcs = { git = "https://github.com/aptos-labs/bcs", rev = "2cde3e8446c460cb17b0c1d6bac7e27e964ac169" } 
borsh = { version = "0.10.0", features = ["rc"]}
byteorder = "1.4.3"
bytes = "1.2.1"
hex = "0.4.3"
once_cell = "1.10.0"
prometheus = { version = "0.13.3", default-features = false }
proptest = "1.0.0"  
proptest-derive = "0.3.0"
rand = "0.8"
rayon = "1.5.2"
serde = { version = "1.0.137", features = ["derive"] }
sha2 = "0.10.6"
thiserror = "1.0.38"
tiny-keccak = "2.0.2"
