[workspace]
resolver = "2"
members = [
    "db/schemadb",
    "db/sovereign-db",
    "demo-app",
    "sdk",
    "adapters/risc0",
    "first-read-last-write-cache",
    "sov-modules/sov-app-template",
    "sov-modules/sov-modules-macros",
    "sov-modules/sov-state",
    "sov-modules/sov-modules-api",
    "sov-modules/sov-modules-impl/accounts",
    "sov-modules/sov-modules-impl/bank",
    "sov-modules/sov-modules-impl/prover-incentives",
    "sov-modules/sov-modules-impl/sequencer",
    "sov-modules/sov-modules-impl/module-template",
    "sov-modules/sov-modules-impl/examples/value-setter",
    "sov-modules/sov-modules-impl/examples/election",
    "sov-modules/sov-modules-impl/integration-tests",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Sovereign Labs <info@sovereign.xyz>"]
homepage = "sovereign.xyz"
publish = false
repository = "https://github.com/sovereign-labs/sovereign"
rust-version = "1.66"

[workspace.dependencies]
# Dependencies maintained by sovereign
jmt = { git = "https://github.com/penumbra-zone/jmt.git", rev = "3ca60665bee78549b37bab5ec461d108dada874d", default-features = false }

# External dependencies
anyhow = "1.0.68"
borsh = { version = "0.10.2", features = ["rc"] }
byteorder = "1.4.3"
bytes = "1.2.1"
hex = "0.4.3"
once_cell = "1.10.0"
prometheus = { version = "0.13.3", default-features = false }
proptest = "1.0.0"
proptest-derive = "0.3.0"
rand = "0.8"
rayon = "1.5.2"
rocksdb = { version = "0.19.0", features = ["lz4"] }
serde = { version = "1.0.137", features = ["derive", "rc"] }
serde_json = { version = "1.0" }
sha2 = "0.10.6"
thiserror = "1.0.38"
tiny-keccak = "2.0.2"
tracing = "0.1.37"
bech32 = "0.9.1"
derive_more = "0.99.11"
toml = "0.7"