[workspace]
resolver = "2"
members = [
	"sdk"
]


[workspace.dependencies]
# External dependencies
anyhow = "1.0.68"
borsh = { version = "0.10.0", features = ["rc"]}
bytes = "1.2.1"
proptest = "1.0.0"  
sha2 = "0.10.6"
thiserror = "1.0.38"
