[package]
name = "integration-tests"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
readme = "README.md"
resolver = "2"
publish = false

[dev-dependencies]
anyhow = { workspace = true }
borsh = { workspace = true, features = ["rc"] }
serde_json = { workspace = true }
serial_test = "*"

sov-modules-api = { path = "../../sov-modules-api"}
sov-modules-macros = { path = "../../sov-modules-macros" }
sov-state = { path = "../../sov-state", features = ["temp"] }
sov-rollup-interface = { path = "../../../rollup-interface" }
sov-schema-db = { path = "../../../full-node/db/sov-schema-db", features = ["temppath"] }
