[package]
name = "sov-default-stf"
version = "0.1.0"
edition = "2021"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
borsh = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tracing = { workspace = true }
jmt = { workspace = true }

sov-rollup-interface = { path = "../../rollup-interface" }
sov-state = { path = "../sov-state", default-features = false }
sov-modules-api = { path = "../sov-modules-api", default-features = false }
