[package]
name = "sov-rollup-interface"
version = "0.1.0"
edition = "2021"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
borsh = { workspace = true, features = ["rc"]}
serde = { workspace = true }
bytes = { workspace = true }
hex = { workspace = true, features = ["serde"] }

anyhow = { workspace = true }
thiserror = { workspace = true }

# Proptest should be a dev-dependency, but those can't be optional
proptest =  { workspace = true, optional = true } 

[dev-dependencies]
serde_json = "1"

[features]
default = []
fuzzing = ["proptest"]
mocks = []
