[package]
name = "methods"
version = "0.2.0"
edition = "2021"
resolver = "2"

[build-dependencies]
risc0-build = { workspace = true }

[package.metadata.risc0]
methods = ["guest"]

[features]
bench = []
