[package]
name = "demo-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
sovereign-sdk = { workspace = true, features = ["mocks"] }
election = { workspace = true }
sequencer = { workspace = true }
bank = { workspace = true }
sov-app-template = { workspace = true }
value-setter = { workspace = true }
accounts = { workspace = true }
sov-state = { path = "../sov-modules/sov-state", features = ["temp"] }
sovereign-db = { workspace = true }
sov-modules-api = { path = "../sov-modules/sov-modules-api", features = ["mocks"] }
sov-modules-macros = { path = "../sov-modules/sov-modules-macros" }
borsh = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }
first-read-last-write-cache = { workspace = true }
schemadb = { workspace = true, features = ["temppath"] }
