[package]
name = "sov-schema-db"
description = "A low level interface transforming RocksDB into a type-oriented data store"
license = "Apache-2.0" # This license is inherited from Aptos 

# Workspace inherited keys
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

readme = "README.md"

[dependencies]
# External dependencies 
anyhow = { workspace = true }
once_cell = { workspace = true, optional = true, default-features = true }
prometheus = { workspace = true, optional = true }
rocksdb = { workspace = true, optional = true }
tracing = { workspace = true }
thiserror = { workspace = true, optional = true }

sov-rollup-interface = { path = "../../../rollup-interface", default-features = false }

[dev-dependencies]
byteorder = { workspace = true, default-features = true }
tempfile = { workspace = true }

[features]
default = ["std"]
std = [
    "anyhow/default",
    "once_cell",
    "prometheus",
    "rocksdb",
    "sov-rollup-interface/default",
    "thiserror",
    "tracing/default",
]

[[test]]
name = "db_test"
required-features = ["std"]

[[test]]
name = "iterator_test"
required-features = ["std"]
