version: '3'

services:
  validator:
    container_name: sov-celestia-validator
    image: ghcr.io/celestiaorg/celestia-app:v0.13.2
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:26657/block?height=1" ]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      - VALIDATOR_NAME=validator1
      - KEY_NAME_1=validator1
      - KEY_NAME_2=validator2
      - KEY_NAME_3=validator3
      - CHAIN_ID=sov-testnet
      - CELES_AMOUNT=12300000000000000000000000utia
      - STAKING_AMOUNT=1000000000utia
      - DEBIAN_FRONTEND=noninteractive
    ports:
      - "9090:9090"
      - "36656:26656"
      - "36657:26657"
      - "36658:26658"
    entrypoint:
      - /bin/sh
      - -c
      - |
        apk update && apk add curl && \
        /bin/celestia-appd init $$VALIDATOR_NAME --chain-id $$CHAIN_ID && \
        /bin/celestia-appd keys add $$KEY_NAME_1 --keyring-backend test && \
        /bin/celestia-appd keys add $$KEY_NAME_2 --keyring-backend test && \
        /bin/celestia-appd keys add $$KEY_NAME_3 --keyring-backend test && \
        /bin/celestia-appd add-genesis-account $$KEY_NAME_1 $$CELES_AMOUNT --keyring-backend test && \
        /bin/celestia-appd add-genesis-account $$KEY_NAME_2 $$CELES_AMOUNT --keyring-backend test && \
        /bin/celestia-appd add-genesis-account $$KEY_NAME_3 $$CELES_AMOUNT --keyring-backend test && \
        /bin/celestia-appd gentx $$KEY_NAME_1 $$STAKING_AMOUNT --chain-id $$CHAIN_ID --keyring-backend test --evm-address 0x966e6f22781EF6a6A82BBB4DB3df8E225DfD9488 && \
        cat /root/.celestia-app/config/genesis.json && \
        /bin/celestia-appd collect-gentxs && \
        echo "NODE_ID:" && \
        /bin/celestia-appd tendermint show-node-id && \
        cp -r /root/.celestia-app/keyring-test /root/keyring-test && \
        /bin/celestia-appd start --rpc.laddr tcp://0.0.0.0:26657 --proxy_app tcp://0.0.0.0:26658
    volumes:
      - ./keyring-test:/root/keyring-test/

  bridge:
    image: ghcr.io/celestiaorg/celestia-node:v0.7.1
    container_name: sov-celestia-bridge
    environment:
      - KEY_NAME=validator1
      - CHAIN_ID=sov-testnet
      - STAKING_AMOUNT=1000000000utia
      - DEBIAN_FRONTEND=noninteractive
    depends_on:
      - validator
    ports:
      - "26656:26656"
      - "26657:26657"
      - "26658:26658"
    entrypoint:
      - /bin/sh
      - -c
      - |
        apt-get update && apt install -y curl jq && rm -rf /var/lib/apt/lists/* && \
        until curl http://validator:26657/block?height=1; do echo "Waiting for validator..."; sleep 5; done && \
        /celestia bridge init --node.store /bridge && \
        until curl http://validator:26657/block?height=1; do echo "Waiting for validator..."; sleep 5; done && \
        export GENESIS=$(curl http://validator:26657/block?height=1 | jq '.result.block_id.hash' | tr -d '"') && \
        cp -r /root/keyring-test /bridge/keys/ && \
        export CELESTIA_CUSTOM="$$CHAIN_ID:$$GENESIS" && \
        echo "Starting bridge with option=$$CELESTIA_CUSTOM and key name $$KEY_NAME" && \
        /celestia bridge start --node.store /bridge --gateway --gateway.addr 0.0.0.0 --rpc.addr 0.0.0.0 --core.ip validator --keyring.accname $$KEY_NAME
    volumes:
      - ./keyring-test:/root/keyring-test




# TODO:
#  * Create keys only if keyring-test does not exist
#  * Export validator API key to file.
#  * Multiple bridges
#  * Bridge health-check
#  * Timeoutable wait for block_height



# GENESIS=""; CNT=0; MAX=30; while [ "${#GENESIS}" -le 4 -a $CNT -ne $MAX ]; do GENESIS=$(curl -s http://127.0.0.1:26657/block?height=1 | jq '.result.block_id.hash' | tr -d '"'); ((CNT++)); sleep 1; done
# GENESIS=""; CNT=0; MAX=30; while [ "${#GENESIS}" -le 4 -a $CNT -ne $MAX ]; do GENESIS=$(curl -s http://127.0.0.1:26657/block?height=1 | jq '.result.block_id.hash' | tr -d '"'); ((CNT++)); sleep 1; done && \