[package]
name = "sov-prover-incentives"
description = "A Sovereign SDK module for incentivizing provers"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
readme = "README.md"
resolver = "2"

[dev-dependencies]
sov-rollup-interface = { path = "../../../rollup-interface", version = "0.1", features = ["mocks"] }
sov-modules-api = { path = "../../sov-modules-api", version = "0.1"}
tempfile = { workspace = true }

[dependencies]
anyhow = { workspace = true }
sov-bank = { path = "../sov-bank", version = "0.1", default-features = false }
sov-modules-api = { path = "../../sov-modules-api", version = "0.1", default-features = false }
sov-modules-macros = { path = "../../sov-modules-macros", version = "0.1" }
sov-state = { path = "../../sov-state", version = "0.1", default-features = false }
sov-rollup-interface = { path = "../../../rollup-interface", version = "0.1" }
serde = { workspace = true }
serde_json = { workspace = true, optional = true }
thiserror = { workspace = true }
borsh = { workspace = true, features = ["rc"] }
# TODO: Replace with serde-compatible borsh implementation when it becomes availabile 
# see https://github.com/Sovereign-Labs/sovereign/issues/215
bincode = "1.3.3"


[features]
default = ["native"]
serde = ["dep:serde_json"]
native = ["serde", "sov-modules-api/native"]
