[package]
name = "sov-state"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]

anyhow = { workspace = true }
borsh = { workspace = true}
serde = { workspace = true }
thiserror = { workspace = true }
sovereign-db = { path = "../../full-node/db/sovereign-db", optional = true}
first-read-last-write-cache = { path = "../utils/first-read-last-write-cache" }
jmt = { workspace = true }
hex = { workspace = true}
sha2 = { workspace = true}

[dev-dependencies]
sovereign-db = { path = "../../full-node/db/sovereign-db", features = ["temp"] }
schemadb = { path = "../../full-node/db/schemadb", features = ["temppath"] }

[features]
default = ["native"]
temp = ["sovereign-db/temp"]
native = ["sovereign-db"]
