[package]
name = "sov-modules-api"
description = "Defines the interface of the Sovereign SDK module system"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
readme = "README.md"
resolver = "2"

[dependencies]
jsonrpsee = { workspace = true, optional = true }
anyhow = { workspace = true }
sov-state = { path = "../sov-state", version = "0.1" }
sov-rollup-interface = { path = "../../rollup-interface", version = "0.1" }
sov-modules-macros = { path = "../sov-modules-macros", version = "0.1", optional = true }
sov-sequencer = { path = "../../full-node/sov-sequencer", optional = true }
serde = { workspace = true }
borsh = { workspace = true }
thiserror = { workspace = true }
sha2 = { workspace = true }
bech32 = { workspace = true }
derive_more = { workspace = true }
serde_json = { workspace = true, optional = true }
hex = { workspace = true, optional = true }
clap = { workspace = true, optional = true }
schemars = { workspace = true, optional = true, features = [] }

# TODO: try update 2.x
ed25519-dalek = { version = "1.0.1", default-features = false, features = ["u64_backend"] }
rand = { version = "0.7", optional = true }

zk-cycle-macros = { path = "../../utils/zk-cycle-macros", optional = true }
risc0-zkvm = { version = "0.16", default-features = false, features = ["std"], optional = true }
risc0-zkvm-platform = { version = "0.16", optional = true }

[dev-dependencies]
bincode = { workspace = true }

[features]
bench = ["zk-cycle-macros", "risc0-zkvm", "risc0-zkvm-platform"]
default = ["macros"]
serde = ["dep:serde_json"]
native = ["serde", "rand", "hex", "schemars", "ed25519-dalek/default", "clap", "jsonrpsee", "macros", "sov-modules-macros/native", "sov-state/native", "sov-sequencer"]
macros = ["sov-modules-macros"]
