[package]
name = "sov-modules-api"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
anyhow = { workspace = true }
sov-state = { path = "../sov-state", default-features = false }
sov-rollup-interface = { path = "../../rollup-interface" }
serde = { workspace = true }
borsh = { workspace = true }
thiserror = { workspace = true }
jmt = { workspace = true }
sha2 = { workspace = true }
bech32 = { workspace = true }
derive_more = { workspace = true }

ed25519-dalek = { version = "1.0.1", default-features = false, features = ["alloc", "u64_backend"]}
rand = {version = "0.7", optional = true}
hex = { workspace = true, optional = true }

[dev-dependencies]
serde_json = { workspace = true }

[features]
default = ["native"]
native = ["sov-state/native", "rand", "hex", "ed25519-dalek/default"]
