[package]
name = "sov-state"
version = "0.1.0"
edition = "2021"

[dependencies]
# TODO remove this dependency once the  Decode/Encode traits are extracted to a separate crate.
anyhow = { workspace = true }
thiserror = { workspace = true }
sovereign-db = { workspace = true }
sovereign-sdk = { workspace = true }
first-read-last-write-cache = { workspace = true }
jmt = { workspace = true }
hex = { workspace = true}

[dev-dependencies]
sovereign-db = { workspace = true, features = ["temp"] }

[features]
default = []
temp = ["sovereign-db/temp"]
