[package]
name = "sov-state"
version = "0.1.0"
edition = "2021"

[dependencies]
# TODO remove this dependency once the  Decode/Encode traits are extracted to a separate crate.
anyhow = { workspace = true }
borsh = { workspace = true}
thiserror = { workspace = true }
sovereign-db = { workspace = true }
sovereign-sdk = { workspace = true, features = ["mocks"] }
first-read-last-write-cache = { workspace = true }
jmt = { workspace = true }
hex = { workspace = true}
sha2 = { workspace = true}

[dev-dependencies]
sovereign-db = { workspace = true, features = ["temp"] }
schemadb = { workspace = true, features = ["temppath"] }

[features]
default = []
mocks = []
temp = ["sovereign-db/temp"]
