[package]
name = "risc0-adapter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sov-rollup-interface = { path = "../../rollup-interface" }
risc0-zkvm = { version = "0.14", default-features = false, features = ['std'] }
risc0-zkp = { version = "0.14", optional = true }
risc0-circuit-rv32im = { version = "0.14", optional = true }
serde = { workspace = true }
anyhow = { workspace = true }

# TODO: Consider replacing this serialization format
# https://github.com/Sovereign-Labs/sovereign/issues/283
bincode = "1.3.3"


[features]
default = ["native"]
native = ["risc0-zkvm/prove", "dep:risc0-zkp", "dep:risc0-circuit-rv32im"]
