[package]
name = "sov-bank"
description = "A Sovereign SDK managing fungible tokens"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
readme = "README.md"
resolver = "2"

[dependencies]
anyhow = { workspace = true }
borsh = { workspace = true, features = ["rc"] }
clap = { workspace = true, optional = true, features = ["derive"] }
jsonrpsee = { workspace = true, features = ["macros", "client-core", "server"], optional = true }
schemars = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }

sov-modules-api = { path = "../../sov-modules-api", version = "0.1" }
sov-state = { path = "../../sov-state", version = "0.1" }
sov-rollup-interface = { path = "../../../rollup-interface", version = "0.1" }
thiserror = { workspace = true }
hex = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[features]
default = []
serde = ["dep:serde", "dep:serde_json"]
native = ["serde", "dep:jsonrpsee", "dep:clap", "dep:schemars", "sov-state/native", "sov-modules-api/native", ]
cli = ["native"]
