[package]
name = "sov-app-template"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
borsh = { workspace = true }

sovereign-sdk = { path = "../../sdk" }
sov-state = { path = "../sov-state", default-features = false }
sov-modules-api = { path = "../sov-modules-api", default-features = false }
