[package]
name = "sov-data-generators"
description = "A set of generator utils used to automatically produce and serialize transaction data"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
readme = "README.md"
resolver = "2"


[dependencies]
sov-modules-api = { path = "../../sov-modules-api" }
sov-modules-stf-template = { path = "../../sov-modules-stf-template" }
sov-value-setter = { path = "../../module-implementations/examples/sov-value-setter", default-features = false }
sov-election = { path = "../../module-implementations/examples/sov-election", default-features = false }
sov-bank = { path = "../../module-implementations/sov-bank", default-features = false }
sov-state = { path = "../../sov-state" }
sov-rollup-interface = { path = "../../../rollup-interface", features = ["mocks"] }

borsh = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }

[features]
default = ["mocks", "native"]

mocks = []
native = []