[package]
name = "prover-incentives"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dev-dependencies]
sovereign-sdk = { path = "../../../sdk", features = ["mocks"] }
sov-modules-api = { path = "../../sov-modules-api"}
sov-state = { path = "../../sov-state", features = ["temp"] }

[dependencies]
anyhow = { workspace = true }
bank = { path = "../bank", default-features = false }
sov-modules-api = { path = "../../sov-modules-api", default-features = false }
sov-modules-macros = { path = "../../sov-modules-macros" }
sov-state = { path = "../../sov-state", default-features = false }
sovereign-sdk = { path = "../../../sdk" }
serde = { workspace = true }
serde_json = { workspace = true, optional = true }
thiserror = { workspace = true }
borsh = { workspace = true, features = ["rc"] }
# TODO: Replace with serde-compatible borsh implementation when it becomes availabile 
# see https://github.com/Sovereign-Labs/sovereign/issues/215
bincode = "1.3.3"


[features]
default = ["native"]
serde = ["dep:serde_json"]
native = ["serde", "sov-modules-api/native"]
