[package]
name = "sov-modules-stf-template"
description = "Defines a generic state transition function for use with the Sovereign SDK module system"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
readme = "README.md"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
borsh = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tracing = { workspace = true }
jmt = { workspace = true }
hex = { workspace = true }

sov-rollup-interface = { path = "../../rollup-interface" }
sov-state = { path = "../sov-state", default-features = false }
sov-modules-api = { path = "../sov-modules-api", default-features = false }
