[package]
name = "sov-modules-macros"
version = "0.1.0"
edition = "2021"
resolver = "2"
autotests = false

[lib]
proc-macro = true

[[test]]
name = "tests"
path = "tests/all_tests.rs"

[dev-dependencies]
trybuild = "1.0"
sov-modules-api = { path = "../sov-modules-api"}
jsonrpsee = { version = "0.16.2", features = ["macros", "client-core", "server"] }
sov-state = { path = "../sov-state", features = ["temp"] }
sovereign-db = { path = "../../full-node/db/sovereign-db", features = ["temp"] }

[dependencies]
anyhow = { workspace = true }
jsonrpsee = { workspace = true, features = ["http-client", "server"]}
sov-modules-api = { path = "../sov-modules-api", default-features = false }
sov-rollup-interface = { path = "../../rollup-interface" }


syn = { version = "1.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
borsh = { workspace = true }
