[package]
name = "sov-zk-cycle-utils"
authors = { workspace = true }
description = "Utilities for counting risc0 cycles consumed by Sovereign SDK functions"
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
readme = "README.md"
resolver = "2"
autotests = false

[dependencies]
risc0-zkvm = { workspace = true, default-features = false, features = ['std'] }
risc0-zkvm-platform = { workspace = true }
bytes = "=1.4.0" # Risc0 re-exports bytes, but it's feature gated. So, we re-import the correct version
