[package]
name = "sov-modules-macros"
version = "0.1.0"
edition = "2021"
autotests = false

[lib]
proc-macro = true

[[test]]
name = "tests"
path = "tests/all_tests.rs"

[dev-dependencies]
trybuild = "1.0"
sov-modules-api = { workspace = true ,  features = ["mocks"]}
jsonrpsee = { version = "0.16.2", features = ["macros", "client-core", "server"] }
sov-state = {workspace = true, features = ["temp"]}
sovereign-db = {workspace = true, features = ["temp"]}

[dependencies]
anyhow = { workspace = true }
sov-modules-api = { workspace = true }
sovereign-sdk = { workspace = true}


syn = { version = "1.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
borsh = { workspace = true }
