[package]
name = "demo-stf"
version = "0.1.0"
edition = "2021"
resolver = "2"

[[bin]]
name = "bank-cmd"
path = "src/bank_cmd/main.rs"
required-features = ["native"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true}
borsh = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true, optional = true }
sha2 = { workspace = true }
clap = { workspace = true, optional = true }
toml = { workspace = true, optional = true }

sovereign-core = { path = "../../core" }
election = { path = "../../module-system/module-implementations/examples/election", default-features = false }
sequencer = { path = "../../module-system/module-implementations/sequencer", default-features = false }
bank = { path = "../../module-system/module-implementations/bank", default-features = false }
sov-app-template = { path = "../../module-system/sov-app-template" } # no features available
value-setter = { path = "../../module-system/module-implementations/examples/value-setter", default-features = false }
accounts = { path = "../../module-system/module-implementations/accounts", default-features = false }
sov-state = { path = "../../module-system/sov-state", default-features = false }
sov-modules-api = { path = "../../module-system/sov-modules-api", default-features = false }
sov-modules-macros = { path = "../../module-system/sov-modules-macros" }
# Only enable the db on "native" feature
schemadb = { path = "../../full-node/db/schemadb", features = ["temppath"], optional = true }
sovereign-db = { path = "../../full-node/db/sovereign-db", optional = true }

[dev-dependencies]
sovereign-core = { path = "../../core", features = ["mocks"] }
tempfile = "3.5.0"

[features]
default = ["native"]
native = ["sov-state/temp", "dep:sovereign-db", "dep:schemadb", "bank/native", "accounts/native", "election/native", 
	"sequencer/native", "value-setter/native", "sov-modules-api/native","sovereign-core/mocks", "clap", "serde_json", "toml"]
verifier = []
