[package]
name = "demo-nft-module"
version = "0.1.0"
edition = "2021"
authors = ["Sovereign Labs <info@sovereign.xyz>"]
homepage = "sovereign.xyz"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
borsh = { workspace = true, features = ["rc"] }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }

sov-modules-api = { path = "../../module-system/sov-modules-api", default-features = false }
sov-modules-macros = { path = "../../module-system/sov-modules-macros" }
sov-state = { path = "../../module-system/sov-state", default-features = false }

[dev-dependencies]
sov-state = { path = "../../module-system/sov-state", features = ["temp"] }
sov-rollup-interface =  { path = "../../rollup-interface" }


[features]
default = ["native"]
serde = ["dep:serde", "dep:serde_json"]
native = ["serde", "sov-state/native", "sov-modules-api/native"]