[package]
name = "sov-sequencer-registry"
description = "A Sovereign SDK module for registering rollup sequencers"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
readme = "README.md"

resolver = "2"

[dev-dependencies]
sov-sequencer-registry = { path = ".", features = ["native"] }
sov-rollup-interface = { path = "../../../rollup-interface", version = "0.2", features = ["mocks"] }
tempfile = { workspace = true }

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, optional = true }
sov-bank = { path = "../sov-bank", version = "0.2" }
sov-modules-api = { path = "../../sov-modules-api", version = "0.2" }
sov-state = { path = "../../sov-state", version = "0.2" }
schemars = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
borsh = { workspace = true, features = ["rc"] }
jsonrpsee = { workspace = true, features = ["macros", "client-core", "server"], optional = true }
sov-zk-cycle-macros = { path = "../../../utils/zk-cycle-macros", version = "0.2", optional = true }
risc0-zkvm = { workspace = true, default-features = false, features = ["std"], optional = true }
risc0-zkvm-platform = { workspace = true, optional = true }
sov-zk-cycle-utils = { path = "../../../utils/zk-cycle-utils", version = "0.2", optional = true }

[features]
bench = ["sov-zk-cycle-macros/bench", "risc0-zkvm", "risc0-zkvm-platform", "sov-zk-cycle-utils"]
default = []
native = [
    "serde",
    "serde_json",
    "jsonrpsee",
    "schemars",
    "clap",
    "sov-state/native",
    "sov-modules-api/native",
    # This:
    "sov-bank/native",
]
