[package]
name = "sov-db"
version = "0.1.0"
edition = "2021"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Maintained by sovereign labs
jmt = { workspace = true }
sov-schema-db = { path = "../sov-schema-db" }
sov-rollup-interface = { path = "../../../rollup-interface" }


# External
anyhow = { workspace = true }
byteorder = { workspace = true }
borsh = { workspace = true }
serde = { workspace = true, features = ["derive"] }
rocksdb = { workspace = true }

bincode = "1.3.3"

[dev-dependencies]
sov-schema-db = { path = "../sov-schema-db", features = ["temppath"] }

[features]
default = []
temp = ["sov-schema-db/temppath"]
