[package]
name = "sov-db"
description = "A high-level DB interface for the Sovereign SDK"
license = "Apache-2.0" # This license is inherited from Aptos 
edition = { workspace = true }
authors = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
readme = "README.md"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Maintained by sovereign labs
jmt = { workspace = true }
sov-schema-db = { path = "../sov-schema-db", version = "0.2" }
sov-rollup-interface = { path = "../../../rollup-interface", version = "0.2", features = ["native", "mocks"] }

# External
anyhow = { workspace = true }
arbitrary = { workspace = true, optional = true }
byteorder = { workspace = true }
borsh = { workspace = true }
proptest = { workspace = true, optional = true }
proptest-derive = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"] }
tempfile = { workspace = true, optional = true }
rocksdb = { workspace = true }
bincode = { workspace = true }
tokio = { workspace = true }


[dev-dependencies]
tempfile = { workspace = true }


[features]
arbitrary = [
    "dep:arbitrary",
    "dep:proptest",
    "dep:proptest-derive",
    "dep:tempfile"
]
