[package]
name = "sov-demo"
version = "0.1.0"
edition = "2021"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
borsh = { workspace = true, features = ["bytes"] }
jsonrpsee = { workspace = true, features = ["http-client", "server"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha2 = { workspace = true }
tracing = { workspace = true }
hex = { workspace = true }
bytes = { workspace = true }

# Crates which only this package depends on 
tendermint = "0.32"
tokio = { version = "1", features = ["full"] }
tracing-subscriber = "0.3.16"

jupiter = { path = "../../adapters/celestia" }
demo-stf = { path = "../demo-stf", features = ["native"] }
sov-rollup-interface = { path = "../../rollup-interface" }
sovereign-db = { path = "../../full-node/db/sovereign-db" }
risc0-adapter = { path = "../../adapters/risc0" }
sov-app-template = { path = "../../module-system/sov-app-template" }

bank = { path = "../../module-system/module-implementations/bank", default-features = false }
election = { path = "../../module-system/module-implementations/examples/election", default-features = false }
value-setter = { path = "../../module-system/module-implementations/examples/value-setter", default-features = false }
sov-modules-api = { path = "../../module-system/sov-modules-api", features=["native"] }
sov-state = { path = "../../module-system/sov-state", features=["native"] }
futures = "0.3"

[dev-dependencies]
tempfile = "3.5.0"
