[package]
name = "sov-demo"
version = "0.1.0"
edition = "2021"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
borsh = { workspace = true, features = ["bytes"] }
jsonrpsee = { workspace = true, features = ["http-client", "server"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha2 = { workspace = true }
tracing = { workspace = true }
hex = { workspace = true }

# Crates which only this package depends on 
tendermint = "0.32"
tokio = { version = "1", features = ["full"] }
tracing-subscriber = "0.3.16"

jupiter = { git = "https://github.com/Sovereign-Labs/Jupiter.git", rev = "afe0beacd4eeb1ea1ccc7b7020e3ba6b9e6b9446" }
demo-stf = { path = "../demo-stf", features = ["native"] }
sovereign-core = { path = "../../core" }
sovereign-db = { path = "../../full-node/db/sovereign-db" }
risc0-adapter = { path = "../../adapters/risc0" }

[dev-dependencies]
tempfile = "3.5.0"
