name: Rust

on:
  push:
    branches: ["research"]
  pull_request:
    branches: ["research"]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v2.2.0
      - name: Run cargo check
        run: cargo check
      - name: Run cargo fmt check
        run: |
          if ! cargo fmt --check ; then
            echo "Formatting errors detected, please rune `cargo fmt` to fix it";
            exit 1
          fi

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v2.2.0
      - name: Run cargo test
        run: cargo test
